### ISSUE TITLE
media keeps original file open.

### ISSUE THREAD

**Issue by modafoe** [MrAliSalehi/Bale.Net#2]
when I send a video and job will done "media" will not release original file and can not remove it.
I sent a video and after that try to remove original video but exception acquired and tells me that the file is in use with another process.

**Comment by MrAliSalehi** [comment]
the unit tests are passing successfully, so I suspect the problem is on your side and not the client itself

can you show your code ?

**Comment by modafoe** [comment]
yes of course:
```
try
                                    {
                                        var client = new BaleClient(token);
                                        _ = client.Attachments.SendVideoAsync(id,Media.FromDisk("wwwroot/test/video.mp4"), message.Caption ?? string.Empty).Result;
                                    }
                                    catch (Exception ex)
                                    {
                                        System.IO.File.AppendAllText("wwwroot/test.txt", DateTime.Now + " error has been equired from sending bale! error = " + ex.Message + '\n');
                                        _ = botClient.SendTextMessageAsync(meid, "Failed!\n" + "Error from sending bale! error = " + ex.Message + "(/cancel)" + '\n').Result;
                                        if (message.Chat.Id != meid)
                                            _ = botClient.SendTextMessageAsync(message.Chat.Id, "Failed error has been equired from sending bale! error = " + ex.Message + "(/cancel)" + "\n").Result;
                                        return;
                                    }
                                    if (System.IO.File.Exists("wwwroot/test/video.mp4"))
                                        System.IO.File.Delete("wwwroot/test/video.mp4");
```

**Comment by MrAliSalehi** [comment]
calling the `.Result` is potentially the problem here, try using `await` instead
let me know if the problem still persists

**Comment by modafoe** [comment]
method send the video correctly. the issue is that i can't remove the original file after that.

**Comment by modafoe** [comment]
"System.IO.File.Delete("wwwroot/test/video.mp4");"

this line get a exception and tells me the file is in use by another process.

**Comment by MrAliSalehi** [comment]
try again and let me know if the issue was solved

**Comment by modafoe** [comment]
thanks. yes the problem solved. and i am surprised that doesn't need to use "using()" for media and Send method disposes media automatically.does it effect all send methods like "SendVideoAsync" , "SendPhotoAsync" and "SendDocumentAsync"?
and I would be very grateful if you update package on nuget too.

**Comment by MrAliSalehi** [comment]
yes, every `Send` method in [IAttachments](https://github.com/MrAliSalehi/Bale.Net/blob/master/Bale.Net/Interfaces/IAttachments.cs) API now will dispose its content automatically, except for `SendContact` & `SendLocation` because they are just raw query parameters and doesn't have any actual "body"

and nuget updated to version 1.0.3
