### ISSUE TITLE
persian filename and extension type in SendDocumentAsync don't work

### ISSUE THREAD

**Issue by modafoe** [MrAliSalehi/Bale.Net#3]
Hi again.
I ran into a new problem.
when i send a file by "SendDocumentAsync" and file name is in persian characters , file sent by name "file" and without any extension file type.
i solved this for eitaa by adding file name in header like this:
```
var streamContent = new StreamContent(new MemoryStream(bytes));
streamContent.Headers.Add("Content-Disposition", new string(Encoding.UTF8.GetBytes("form-data; name=\"file\"; filename=\""+file_name+"\"").Select(b => (char)b).ToArray()));
form.Add(streamContent, "file", file_name);
```
in Bale.Net.Types.Media in line 47 you wrote:
`                multipartFormDataContent.Add(_content, contentName, "file");
`
i think this must be:
`                multipartFormDataContent.Add(_content, "file", contentName);
`
after that the filename will sent to bale correctly but perhaps in encoded format.
to solve this you can send filename in header as like as i said above.
the main problem is MultipartFormDataContent do base64-encoded filenames automatically and for persian characters it is not beautiful.

**Comment by MrAliSalehi** [comment]
i dont think the file name should be persian, its something that will be served by the server and not shown to the end-user

**Comment by modafoe** [comment]
we need to post files with persian name like "وصیت نامه.jpg" and with app it is possible and name will correctly shows on channel.
and i am 99.99% sure that it is possible from api too and if you change code as i said it will be fix.

**Comment by MrAliSalehi** [comment]
the code you suggested will not fix any problem, I sent a fix which will do what you want, hope that helps!
