### ISSUE TITLE
issue in SendVideoAsync method

### ISSUE THREAD

**Issue by modafoe** [MrAliSalehi/Bale.Net#4]
i got the following error in SendVideoAsync. SendPhotoAsync works normally but SendVideoAsync has an exception. last line is important:
> at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
>    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>    at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
>    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
>    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at Bale.Net.Implementations.Attachments.SendAttachmentAsync(Endpoint endpoint, String contentName, Int64 chatId, Media media, String caption, Int64 replayToMessageId)
>    at Bale.Net.Implementations.Attachments.SendVideoAsync(Int64 chatId, Media media, String caption, Int64 replayToMessageId)
>    at Controller.Main(Update update) in {path}
> Error from sending bale! error = No such host is known. (tapi.bale.ai:443)

i haven't any idea what is wrong but i guess the problem may be from dns address. may adding "https" to tapi.bale.ai without port fix it.

**Comment by MrAliSalehi** [comment]
I think they are moving things around, the `https://dev.bale.ai/api` returns 404, as well as the API itself `tapi.bale.ai`.
both of them are down/ or "deleted".
can't do anything about it sadly, just have to wait until they fix it:)

**Comment by modafoe** [comment]
maybe. but how SendPhotoAsync  r working now?
if you r looking for api docs you can access them in:
https://tapi.bale.ai/docs

**Comment by modafoe** [comment]
i tested SendVideoAsync today and it's worked normally.

**Comment by modafoe** [comment]
Bale has been updated docs and api.

**Comment by MrAliSalehi** [comment]
> Bale has been updated docs and api.

I assume there are some breaking changes?

**Comment by modafoe** [comment]
> > Bale has been updated docs and api.
> 
> I assume there are some breaking changes?

yes.
some of them:
- adding some new methods
- set sending message rate per bot
- decrease sending & downloading file size (like telegram) - i don't know this was really applied or just is in api docs -
- api now is very similar to telegram api
- now you can't use both of webhook & getupdate method in the same time.
- change some method params
- some of api methods are still working but in doc it not showing.(balethon is a python package for bale api and in their channel he wrote some of this methods that not mentioned in the docs)
- and much more....

in past bale webhook not working as well and incoming updates be null and i forced to use both webhook and getupdate method same time. i hope that their fix this issue.

**Comment by MrAliSalehi** [comment]
alright, thanks for the update, I'll update the library to the latest changes

**Comment by MrAliSalehi** [comment]
the api does not seem to be fully functional, getUpdate doesn't work properly, nor does the ReplyMarkups, sounds like the devs are 😴

**Comment by modafoe** [comment]
if you set webhook you can't use getupdate func.you must remove webhook first.
but yes in bale developers group they r in communicating to devs and ask them for problems that they r having and tring to fix them.
