### ISSUE TITLE
SendDocumentAsync not working

### ISSUE THREAD

**Issue by modafoe** [MrAliSalehi/Bale.Net#5]
hi. after updating bale api SendDocumentAsync not working.
stacktrace :

`at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bale.Net.Implementations.Attachments.SendAttachmentAsync(Endpoint endpoint, String contentName, Int64 chatId, Media media, String caption, Int64 replayToMessageId)
   at Bale.Net.Implementations.Attachments.SendDocumentAsync(Int64 chatId, Media media, String caption, Int64 replayToMessageId)
   at telegram_bot2.Controllers.BotController2.sendposter(Message message) in {path} : The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.`

**Comment by MrAliSalehi** [comment]
I'll check it

**Comment by MrAliSalehi** [comment]
تست های داکیومنت دارن پاس میشن، احتمالا مشکلی از سمت نتورک شما بوده یا شاید هم به طور موقتی api مشکل داشته

**Comment by modafoe** [comment]
تشکر بابت بررسی.
برنامه روی هاست هستش.قبلا هم کار میکرد همین بخش کد.
ضمن اینکه یک بار این اتفاق نیفتاده و چند سری هست که سند داکیومنت کار نمیکنه و سند داکیومنت دقیقا بعد از SendPhotoAsync استفاده شده و نسخه فشرده شده به درستی ارسال میشه ولی نسخه بدون فشرده شدن گیر میکنه و بعد از 100 ثانیه هم تایم اوت میشه. فایل هم حجمش 26 مگ بود این آخری و حجمی نبود که گیر کنه.

**Comment by MrAliSalehi** [comment]
با فایل 30 مگی هم تست کردم همچنان بدون مشکل تست ها پاس میشن.
تایم اوتی که میده هیچ دلیل دیگه ای نمیتونه داشته باشه بجز اختلال نت یا api 
الان همچنان این ارور رو دارید میگیرید یا هر چند وقت یک بار پیش میاد؟

**Comment by modafoe** [comment]
چون چند باری پیش اومد من ارسال نسخه اصلی عکس رو کلا کامنت کردم از روی بات.
ولی حداقل دو بارشو مطمئنم پیش اومده.اونم با فاصله حدود یک هفته از هم.

**Comment by MrAliSalehi** [comment]
این مدل خطاها زیاد پیش میاد
باید retry policy پیاده سازی بشه، اگه وقت کنم مستقیم روی کتابخونه مینویسمش
فعلا خودتون سمت کد باید هندل کنید اون موضوع رو

**Comment by modafoe** [comment]
حله.
منم حس میکنم احتمالا مشکل از سمت api خود بله باشه وگرنه باید متد های دیگه هم مشکل میداشت. چون بیس url اشون یکیه. شاید محدودیت سرعت گذاشتن روی آپلود.نمیدونم.
فقط یه نکته اضافه کنم که معمولا هاست ها محدودیت اجرای درخواست دارن و این محدودیت حدود 100 تا 120 ثانیه هست یعنی حتی اگر درخواست بعد از 100 ثانیه اجرا ریسپانس نداشته باشه سرور به اجبار میره روی استند بای و کانکشن درخواست هم قطع میشه و امکان اجرای دوباره درخواست نیست. مگر اینکه دوباره سرور کال بشه. یا اینکه به جای هاست از سرور مجازی استفاده کنیم که خوب هزینش خیلی بیشتره.
با اینحال ممنون بابت پیگیری. 👌
