### ISSUE TITLE
update handling

### ISSUE THREAD

**Issue by modafoe** [MrAliSalehi/Bale.Net#6]
Hi.
i can't handle updates perfectly.
i wrote:
`[HttpPost]
[Route("path1/bale")]

public async void Main([FromBody] Bale.Net.Types.Update update)
{
    var client = new BaleClient("token");
    _ = await client.Messages.SendMessageAsync('my chatid', update.UpdateId.ToString());
}`
but update not setting properly.
the error is = Object reference not set to an instance of an object.
i think update type is not exactly same as json that bale will send.
i tested [FromBody] , [FromHeader] ,[FromForm] and null but in other cases this method not called.
is there a mistake by me?

**Comment by MrAliSalehi** [comment]
i havent tested the webhook personally, have you trying the polling method? if the polling fails as well, there is probably a breaking change from the bale api

**Comment by modafoe** [comment]
not yet.
i am getting updates manually by using getupdate method.(just by call main method by webhook and get update manually.)
but by using this method , sometimes i get previous update instead of new one.
so i need to get updates directly from requests.

**Comment by MrAliSalehi** [comment]
can you provide an example to reproduce the issue?

**Comment by MrAliSalehi** [comment]
i've written a simple update handler that i didnt commit (about a year ago), this could potentially simply your work,
take a look at [here](https://github.com/MrAliSalehi/Bale.Net/tree/master/HandleUpdates).
havent looked into webhooks yet

**Comment by modafoe** [comment]
ok i will send my old code for example:
```
[HttpPost]
[Route("path")]
public async void Main([FromBody] Bale.Net.Types.Update update)
{
    //initial config
    var client = new BaleClient("token");
    try
    {
        //get update manually
        if(update == null)
            update = client.Updates.GetUpdatesAsync(-1, 0).Result[0];//sometimes this line return previous update and not last one
.
.
.
    }
    catch{}
```

**Comment by modafoe** [comment]
hi again.
i think i found problem.
when i try to parse original json to update object of bale.net this error equired.
the error is this:
Newtonsoft.Json.JsonReaderException: 'Unexpected character encountered while parsing value: 1. Path 'message.date', line 1, position 156.'
something is wrong when parsing message.date from json to update object.

**Comment by modafoe** [comment]
i fixed this issue by getting json from request and deserializing it to update object manually.
```
Stream req = Request.Body;
req.Seek(0, System.IO.SeekOrigin.Begin);
string json = new StreamReader(req).ReadToEnd();
update = System.Text.Json.JsonSerializer.Deserialize<Update>(json);
```
 using code above instead of GetUpdatesAsync fixed my issue.
